name: Release
on:
  push:
    tags:
      - v*
      - '!v*-beta*'

jobs:
  release:
    name: Release to Github Packages and NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Verify PR is labeled for semver
        uses: jefflinse/pr-semver-bump@v1.0.0
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: breaking
          minor-label: feature
          patch-label: patch
          require-release-notes: false
          with-v: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          scope: '@rtkwlf'
          registry-url: https://npm.pkg.github.com/
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Publish to github packages
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          scope: '@rtkwlf'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}