name: Test
on: [pull_request]

jobs:
  test:
    name: Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Verify PR is labeled for semver
        uses: jefflinse/pr-semver-bump@v1.0.0
        with:
          mode: validate
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          major-label: breaking
          minor-label: feature
          patch-label: patch
          require-release-notes: false
          with-v: true
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Prettier
        run: npm run prettier:check
      - name: Test
        run: npm run test:coverage
        continue-on-error: true
      - name: Build
        run: npm run build
